services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acai_gest_frontend
    restart: always
    ports:
      - "127.0.0.1:8080:80"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
